### ISSUE TITLE
Newest version reads incorrectly in PT4

### ISSUE THREAD

**Issue by ayang034** [matt57225/bovada-hand-history-converter#5] opened 2018-06-25 02:05 UTC
First of all, thanks for building this app, been using it on and off for a few years. Loaded it up for the first time in >1yr and when I converted an HH, PT4 read the win summary wrong.

> For example, PokerStars Zoom Hand #3621162780:  Hold'em No Limit ($0.02/$0.05) - 2018/06/23 14:10:20 ET
> Table 'Zone Poker ID 1256 6-max' 6-max Seat #5 is the button
> Seat 1: Seat 1 ($11.74 in chips)
> Seat 2: Seat 2 ($3.95 in chips)
> Seat 3: Seat 3 ($6.60 in chips)
> Seat 4: Seat 4 ($5.05 in chips)
> Seat 5: Seat 5 ($5.09 in chips)
> Seat 6: Hero ($4.62 in chips)
> Hero: posts small blind $0.02
> Seat 1: posts big blind $0.05
> *** HOLE CARDS ***
> Dealt to Hero [Ac As]
> Seat 2: folds
> Seat 3: folds
> Seat 4: folds
> Seat 5: raises $0.05 to $0.10
> Hero: raises $0.30 to $0.40
> Seat 1: calls $0.35
> Seat 5: folds
> *** FLOP *** [3c Js 6s]
> Hero: bets $0.30
> Seat 1: calls $0.30
> *** TURN *** [3c Js 6s] [3s]
> Hero: checks
> Seat 1: bets $0.85
> Hero: raises $3.07 to $3.92 and is all-in
> Seat 1: calls $3.07
> *** RIVER *** [3c Js 6s 3s] [6h]
> *** SHOW DOWN ***
> Seat 3: shows [4c 5s] (a hand...)
> Seat 2: shows [6c Td] (a hand...)
> Seat 1: shows [Jd Qh] (a hand...)
> Hero: shows [Ac As] (a hand...)
> Seat 5: shows [7d 9d] (a hand...)
> Seat 4: shows [9c 8h] (a hand...)
> Hero collected $8.88 from pot
> *** SUMMARY ***
> Total pot $9.34 | Rake $0.46
> Board [3c Js 6s 3s 6h]
> Seat 1: Seat 1 showed [Jd Qh] and lost with...
> Seat 2: Seat 2 folded
> Seat 3: Seat 3 folded
> Seat 4: Seat 4 folded
> Seat 5: Seat 5 folded
> Seat 6: Hero showed [Ac As] and won ($8.88)

When using the current version of the converter, PT4 reads that C won for Hero is $8.88+$4.62. When I revert to an older version, it correctly reads $4.26 as C won. However, there are missing hands, no doubt due to the blinds issue that the most recent version has fixed.

**Comment by matt57225** [comment] 2018-07-21 16:28
Sorry for late response. Please post the original (not converted) hh and I will take a look.

**Comment by AstroSheppard** [comment] 2018-10-13 04:48
I want to add to this. PT4 misreports the winning from the converted hand history file. It seems to roughly report net winnings as TOTAL POT + MONEY PUT IN BY HERO, as opposed to TOTAL POT - MONEY PUT IN BY HERO. For example, it reads the following amount won as $1.28. What follows is first the unconverted hand history, then the converted one. Hopefully these details help diagnose the issue. 

This is all for NL Hold'em Ignition Zone.

> Ignition Hand #3670655814  Zone Poker ID#1301 HOLDEMZonePoker No Limit - 2018-10-09 22:24:02
Seat 1: Small Blind ($10.33 in chips)
Seat 2: Big Blind ($5.22 in chips)
Seat 3: UTG [ME] ($4.37 in chips)
Seat 4: UTG+1 ($2.43 in chips)
Seat 5: UTG+2 ($4.55 in chips)
Seat 6: Dealer ($8.78 in chips)
Dealer : Set dealer [6] 
Small Blind : Small Blind $0.02 
Big Blind : Big blind $0.05 
*** HOLE CARDS ***
Small Blind : Card dealt to a spot [Qh 8c] 
Big Blind : Card dealt to a spot [7d 7h] 
UTG  [ME] : Card dealt to a spot [Ks Jh] 
UTG+1 : Card dealt to a spot [Kd 6c] 
UTG+2 : Card dealt to a spot [9d Ac] 
Dealer : Card dealt to a spot [2d 2s] 
UTG+1 : Leave(Auto)
UTG  [ME] : Raises $0.15 to $0.15
UTG+1 : Folds
Small Blind : Leave(Auto)
UTG+2 : Folds
UTG+2 : Leave(Auto)
Dealer : Calls $0.15 
Small Blind : Folds
Big Blind : Calls $0.10 
*** FLOP *** [9h Td 3h]
Big Blind : Checks
UTG  [ME] : Checks
Dealer : Bets $0.20 
Big Blind : Folds
Big Blind : Leave(Auto)
UTG  [ME] : Calls $0.20 
*** TURN *** [9h Td 3h] [Kh]
UTG  [ME] : Bets $0.50 
Dealer : Folds
Dealer : Leave(Auto)
UTG  [ME] : Return uncalled portion of bet $0.50 
UTG  [ME] : Does not show [Ks Jh] (One pair)
UTG  [ME] : Hand result $0.83 
UTG  [ME] : Leave(Auto)
Enter(Auto)
Enter(Auto)
Enter(Auto)
Enter(Auto)
Enter(Auto)
Enter(Auto)
*** SUMMARY ***


> 
> PokerStars Zoom Hand #3670655814:  Hold'em No Limit ($0.02/$0.05) - 2018/10/09 22:24:02 ET
> Table 'Zone Poker ID 1301' 9-max Seat #6 is the button
> Seat 1: Small Blind ($10.33 in chips) 
> Seat 2: Big Blind ($5.22 in chips) 
> Seat 3: Hero ($4.37 in chips) 
> Seat 4: UTG+1 ($2.43 in chips) 
> Seat 5: UTG+2 ($4.55 in chips) 
> Seat 6: Dealer ($8.78 in chips) 
> Small Blind: posts small blind $0.02
> Big Blind: posts big blind $0.05
> *** HOLE CARDS ***
> Dealt to Hero [Ks Jh]
> Hero: raises $0.10 to $0.15
> UTG+1: folds 
> UTG+2: folds 
> Dealer: calls $0.15
> Small Blind: folds 
> Big Blind: calls $0.10
> *** FLOP *** [9h Td 3h]
> Big Blind: checks 
> Hero: checks 
> Dealer: bets $0.20
> Big Blind: folds 
> Hero: calls $0.20
> *** TURN *** [9h Td 3h] [Kh]
> Hero: bets $0.50
> Dealer: folds 
> *** SHOW DOWN ***
> Big Blind: shows [7d 7h] (a hand...)
> UTG+1: shows [Kd 6c] (a hand...)
> UTG+2: shows [9d Ac] (a hand...)
> Dealer: shows [2d 2s] (a hand...)
> Small Blind: shows [Qh 8c] (a hand...)
> Hero: shows [Ks Jh] (a hand...)
> Uncalled bet ($0.50) returned to Hero
> Hero collected $0.83 from pot
> *** SUMMARY ***
> Total pot $0.07 | Rake $0.04
> Board [9h Td 3h Kh]
> Seat 1: Small Blind folded
> Seat 2: Big Blind folded
> Seat 3: Hero collected ($0.83)
> Seat 4: UTG+1 folded
> Seat 5: UTG+2 folded
> Seat 6: Dealer folded

**Comment by matt57225** [comment] 2018-11-17 04:37
Thank you both for the feedback.  I think the problem is fixed now.

**Closed as completed** 2018-11-17 17:51 UTC
